# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mrrobot97's blog
author: mrrobot97
description: 'Record my study in android.' # write a nice description for your blog
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://mrrobot97.github.io' # the base hostname & protocol for your site http://www.example.com
# google_analytics: 'UA-XXXXXX-X'
github_username: 'mrrobot97'

# Build settings
markdown: kramdown

gems: [jekyll-paginate]

paginate: 10
paginate_path: "/page:num"
